[cerebrium.deployment]
name = "hugging-face-starter"
python_version = "3.12"
docker_base_image_url = "debian:bookworm-slim"
include = "[./*, main.py, cerebrium.toml]"
exclude = "[.*]"

[cerebrium.hardware]
provider = "aws"
region = "eu-west-3"
compute = "AMPERE_A10"
cpu = 4
memory = 18.0
gpu_count = 1

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 30

[cerebrium.dependencies.pip]
diffusers = "latest"
torch = "latest"
transformers = "latest"

